name: Locust Test
on:
  push:
    branches:
      - master
      - develop
      - feature/locust
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: "*/60 * * * *"
jobs:
  deploy:
    runs-on:
      ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/locust
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install locust
      - name: Start locust
        run: |
          cd tests/src/load
          locust --headless --run-time 30s --users 1 --spawn-rate 1 --host http://52.203.15.233:8000 
        
