# # This is a basic workflow to help you get started with Actions

# name: Sphinx Action

# # Controls when the action will run. Triggers the workflow on push
# # for master branch only
# on:
#   commit:
#     branches: [ enhance/documentation ]

# # A workflow run is made up of one or more jobs that can run
# # sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-20.04
#     # Steps represent a sequence of tasks that will be executed
#     # as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your
#     # job can access it
#     - uses: actions/checkout@v2

#     - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.8'

#     - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install sphinx==4.2.0
#           pip install sphinx_rtd_theme==1.0.0
#           python setup.py install

#     - name: Build Documentation
#         run: |
#           cd docs
#           sphinx-apidoc -o source ../src/galaxy
#           sphinx-apidoc -o source ../API
#           make html

#     - name: Deploy HTML
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./html
#         publish_branch: gh-pages

name: Sphinx Action
on:
  commit:
    branches:
      - enhance/documentation
  # push:
  #   branches:
  #     - bug/unittest
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build:
    runs-on:
      ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
    - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx==4.2.0
          pip install sphinx_rtd_theme==1.0.0
          python setup.py install

    - name: Build Documentation
        run: |
          cd docs
          sphinx-apidoc -o source ../src/galaxy
          sphinx-apidoc -o source ../API
          make html

    - name: Deploy HTML
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages